const ProgresTrackerData = [
  {
    vendor_category: "venue",
    preparations: {
      title: "H-1 - VENUE PREPARATION & SETUP",
      tasks: [
        {
          task_name: "Akses venue dibuka untuk persiapan H-1",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "PIC venue hadir & standby di lokasi",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Area acara clear dari event / aktivitas sebelumnya",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Jalur loading vendor dibuka & dapat dilalui",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Titik drop-off / loading bay vendor ditetapkan",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Area parkir & staging vendor siap digunakan",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Jalur service (lift / corridor) dapat dipakai vendor",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name:
            "Zoning area acara dikonfirmasi (stage, seating, catering, vendor)",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Kebersihan awal venue selesai sebelum instalasi vendor",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Listrik utama venue aktif & stabil",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name:
            "Daya listrik sesuai kesepakatan tersedia (panel, MCB, titik colokan)",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Backup listrik (genset / UPS jika ada) siap & diuji",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "AC / ventilasi aktif untuk kebutuhan instalasi",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "House lighting venue berfungsi normal",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Akses air bersih tersedia untuk vendor",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name:
            "Ruang rias / preparation room siap (meja, kursi, listrik, AC)",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Backstage / vendor room tersedia & siap digunakan",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Area dapur / pantry catering siap digunakan",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name:
            "Aturan venue terkait rigging, floor & dinding dikonfirmasi ulang",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Pembersihan akhir H-1 setelah instalasi vendor",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Area venue aman untuk ditinggal overnight",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
      ],
    },
    readiness_check: {
      title: "DAY-OF — PRE-OPENING READINESS CHECK",
      tasks: [
        {
          task_name: "Venue dibuka kembali sesuai jadwal Day-Of",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "PIC venue standby & siap koordinasi Day-Of",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Kondisi area utama dicek ulang (bersih & aman)",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "AC, listrik, & pencahayaan aktif sesuai jam acara",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Toilet tamu siap (air, lampu, kebersihan, tisu, sabun)",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Toilet crew / vendor siap (jika ada)",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Holding room / ruang tunggu keluarga / VIP siap",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Jalur evakuasi clear & tidak terhalang instalasi)",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "APAR / fire extinguisher terlihat & dapat diakses",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Koordinasi keamanan venue untuk kontrol akses tamu",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Sistem komunikasi on-site aktif (PIC, WA group, HT))",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Area utama venue rapi & siap terima tamu",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
        {
          task_name: "Venue dinyatakan READY untuk opening gate tamu",
          time_started: "",
          time_completed: "",
          pic: "",
          priority: "normal",
          status: "completed",
          notes: "",
          image_url: "https://drive.google.com/file/d/1P6fCPMtGzY6KnULXjoEW8zDvU3_LW3dO/view?usp=drive_link",
        },
      ],
    },
    progress_percentage: 100
  },
  {
    vendor_category: "WEDDING ORGANIZER",
    preparations: {
      title: "H-1 — PREPARATION & TECHNICAL SETUP",
      tasks: [
        { task_name: "Tim inti WO/EO tiba di venue (H-1)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "PIC utama WO/EO standby & terkonfirmasi", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Brief internal H-1 (alur kerja & pembagian area)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Review & pemahaman rundown final", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Pembagian tugas detail (floor, stage, backstage, tamu, VIP)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Koordinasi teknis dengan Seremony Lead", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Koordinasi dengan venue (aturan, akses, flow)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Koordinasi awal dengan vendor utama (dekor, catering, teknis)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Penyiapan backstage & holding area", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Penyiapan area terima tamu, tabung amplop, kado, dan souvenir", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Serah terima souvenir", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Bride & Groom Assistant hadir & memahami alur H-1", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Simulasi alur pengantin (datang – persiapan – masuk acara)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Gladi resik / technical run-through", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Evaluasi hasil gladi & penyesuaian minor (jika ada)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Koordinasi cue dengan MC, musik, dan pengisi acara", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Koordinasi dengan dokumentasi terkait momen penting", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Brief akhir H-1 & penutupan persiapan hari pertama", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
      ],
    },
    readiness_check: {
      title: "DAY-OF — PRE-OPENING READINESS CHECK",
      tasks: [
        { task_name: "Tim WO/EO hadir kembali sesuai jadwal Day-Of", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Brief singkat ulang seluruh tim WO/EO", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Final review rundown & timing acara", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Serah terima kunci tabung amplop dan kado kepada pihak seremony / keluarga", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Penempatan floor crew sesuai area", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Bride & Groom Assistant standby & siap tugas", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Koordinasi final dengan vendor utama (status siap)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Koordinasi final cue-in / cue-out dengan MC & musik", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Sistem komunikasi lapangan aktif (WA group / HT)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Kontrol area tamu, VIP, dan backstage", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Brief final seluruh vendor sebelum opening", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "WO/EO menyatakan READY untuk opening acara", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
      ],
    },
    progress_percentage: 50
  },
  {
    vendor_category: "DEKORASI",
    preparations: {
      title: "H-1 — PRODUCTION, LOADING & INSTALLATION",
      tasks: [
        { task_name: "Tim dekorasi tiba di venue sesuai jadwal H-1", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Area loading dekor siap & dapat digunakan", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Barang & properti dekor tiba lengkap sesuai daftar", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Area kerja dekor sesuai zoning venue dikonfirmasi", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Proteksi lantai / dinding / area venue terpasang (jika diperlukan)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Struktur utama dekor / rangka terpasang", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Instalasi backdrop / pelaminan / main stage", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Instalasi area aisle / entrance", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Instalasi seating decoration / table setup", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Instalasi dekor area VIP / keluarga", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Instalasi dekor area catering & stall", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Instalasi dekor area photospot", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Instalasi lighting dekor (jika terpisah dari lighting system)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Penempatan floral utama", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Penempatan properti & detail styling", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Penyesuaian posisi dekor sesuai layout final", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Pembersihan area kerja dekor (sisa packing, alat)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Final check hasil instalasi H-1", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
        { task_name: "Area dekor aman ditinggal overnight", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: "https://drive.google.com/file/d/126vpqI3mT5raqncFX4EPrlrsBUOnz4z1/view?usp=drive_link"},
      ],
    },
    readiness_check: {
      title: "DAY-OF — PRE-OPENING READINESS CHECK",
      tasks: [
        { task_name: "Tim dekor hadir kembali di venue (Day-Of)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Kondisi dekor dicek ulang (tidak rusak / bergeser)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Touch-up floral (penggantian / penyegaran bunga)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Touch-up properti & styling detail", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Penyesuaian minor akibat perubahan teknis lapangan", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Koordinasi posisi dekor dengan lighting & multimedia", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Area acara utama rapi & bersih", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Dekor siap untuk dokumentasi pre-event", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
        { task_name: "Dekor dinyatakan READY sebelum opening gate tamu", time_started: "", time_completed: "", pic: "", priority: "normal", status: "pending", notes: "", image_url: ""},
      ],
    },
    progress_percentage: 70
  },
  {
    vendor_category: "CATERING UTAMA",
    preparations: {
      title: "H-1 — KITCHEN, BUFFET INSTALLATION & SETUP",
      tasks: [
        { task_name: "Tim inti catering tiba di venue (H-1)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "PIC catering standby & terkonfirmasi", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Area dapur / pantry venue diserahkan & siap digunakan", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Jalur loading catering clear & disepakati", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Peralatan dapur utama tiba & dicek kelengkapannya", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Meja prasmanan tiba & sesuai jumlah yang disepakati", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Chafing dish, warmer, kompor, dan alat pemanas tiba", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Piring, sendok, garpu, alat saji, dan perlengkapan buffet lengkap", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Penempatan meja prasmanan sesuai layout final", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Penataan jalur antrean buffet (flow masuk–keluar)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Instalasi peralatan buffet selesai & siap digunakan", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Penempatan area plating & finishing makanan", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Ketersediaan listrik, air, dan gas (jika diperlukan) dikonfirmasi", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Alur kerja dapur & buffet dipahami tim catering", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Brief internal tim dapur & service H-1", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Koordinasi teknis dengan WO/EO & Seremony (timing & flow serving)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Area buffet & dapur rapi dan aman ditinggal overnight", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
      ],
    },
    readiness_check: {
      title: "DAY-OF — FOOD READINESS, SERAH TERIMA & SERVING",
      tasks: [
        { task_name: "Tim dekor hadir kembali di venue (Day-Of)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Tim catering hadir kembali sesuai jadwal Day-Of", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Brief ulang tim dapur & service", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Bahan makanan utama tiba & dicek kualitasnya", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Proses masak dimulai sesuai timeline acara", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Makanan siap saji sesuai menu & porsi", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Pemanasan & final preparation di area buffet", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Area buffet siap saji (display, kebersihan, suhu)", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Serah terima makanan dari Catering ke Seremony Assist", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Serah terima makanan dari Seremony ke Perwakilan Keluarga", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Konfirmasi menu & jumlah porsi sesuai kesepakatan", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Tim service standby di posisi masing-masing", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Koordinasi final waktu serving dengan WO/EO", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Catering utama siap mulai serving", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
        { task_name: "Catering utama dinyatakan READY sebelum opening acara", time_started: "", time_completed: "", pic: "", priority: "normal", status: "completed", notes: "", image_url: ""},
      ],
    },
    progress_percentage: 100
  },
];

export { ProgresTrackerData };
